### ISSUE TITLE
Fully automated process.

### ISSUE THREAD

**Issue by samoht9277** [eth-educators/ethstaker-deposit-cli#283]
The flag `--non_interactive` allows to disable confirmation to some inputs, but seedphrase and password are still required manual inputs, with no way to fully automate the process with a command.

Two new flags (or reading environment variables) to pass the seedphrase and the password would be helpful for advanced users who try to create the deposit data and the keystore automatically. 

A security warning alongside the descriptions should say that this flags are dangerous.

**Comment by samoht9277** [comment]
Thanks for the quick response!

I'm currently trying to fully automate the process of creating a new server, installing all necessary components, waiting for the node to finish syncing, use `cast` to create a new mnemonic, creating the deposit data and keystore automatically, import the keystore to my CL node, parse the deposit data and send the 32ETH with `cast`.

If there's a more optimal way to achieve this, lmk. I'm a DevOps and sort of new to all the Ethereum ecosystem.

**Comment by yorickdowne** [comment]
That `--non-interactive` still requires you to manually handle the mnemonic is tbh by design. It's a new mnemonic, we can't write it into a file!

If you want to automate key handling, you'd create a mnemonic your own way, then use existing-mnemonic

Even better is to use ethstaker-deposit-cli as a library, but somewhere between 0.1.2 and 1.2.0 we broke that. Looking to see where and how ...

**Comment by yorickdowne** [comment]
@jybp and @samoht9277 , I have thoughts on how this could be done. It may be better to have a discussion in ethstaker Discord, for faster back and forth.

The typical flow is:
- Create a mnemonic somehow
- Use existing-mnemonic either via CLI or as a module to make keys

That first part, "create a mnemonic somehow", could be changed to where `new-mnemonic` when run with a parameter we need to define, only spits out a mnemonic, doesn't verify the mnemonic, doesn't create keys. Basically `--no-validator-keys`, or whatever we call it. When `--non-interactive`, it'd do that without verification and without the "wipe clipboard and screen" steps we take.

That way you don't need another tool.

And, it'll always have to be "create mnemonic in some way step 1; use it to make validators step 2" when automating.

Yes, once we know what we want here, it's also possible to have it spit that out as `--json`

**Comment by yorickdowne** [comment]
Very cool. I’ll ping you in the discord. We don’t do DMs. The discord is at discord.gg/ethstaker

**Comment by yorickdowne** [comment]
@jybp Ive sent a fren request. From there I’d like to move to public discussion on discord.gg/ethstaker - but if it’s easier to start on a DM to join that server, let’s.

I do want the discussion to be public.

**Comment by jybp** [comment]
@yorickdowne Accepted and joined discord server.

> The typical flow is:
Create a mnemonic somehow
Use existing-mnemonic either via CLI or as a module to make keys
That first part, "create a mnemonic somehow", could be changed to where new-mnemonic when run with a parameter we need to define, only spits out a mnemonic, doesn't verify the mnemonic, doesn't create keys. Basically --no-validator-keys, or whatever we call it. When --non-interactive, it'd do that without verification and without the "wipe clipboard and screen" steps we take.

> That way you don't need another tool.

> And, it'll always have to be "create mnemonic in some way step 1; use it to make validators step 2" when automating.

> Yes, once we know what we want here, it's also possible to have it spit that out as --json

I think that would work. At the end of the day the need just is:
1. `new-mnemonic`: Ability to programmatically interact with the CLI to:
    a. retrieve the generated mnemonic
    b. retrieve the output filenames for deposit_data+keystore.
2. `existing-mnemonic`: Ability to programmatically pass `--mnemonic` and parse the output filenames for deposit_data+keystore.

Today it's extremely tedious to automate, in part because parsing human outputs (ANSI escape codes) is not that trivial. The ideal solution would be a `--json` flag.

Ideally usage alongside `--non_interactive` for `new-mnemonic` would only output:
```json
{
    "mnemonic": "cherry cherry cherry cherry ...",
    "keystore": "./validator_keys/keystore-123.json",
    "deposit_data": "./validator_keys/deposit_data-123.json"
}
```

And for `existing-mnemonic`:

```json
{
    "keystore": "./validator_keys/keystore-123.json",
    "deposit_data": "./validator_keys/deposit_data-123.json"
}
```

**Comment by remyroy** [comment]
We implemented a 2 steps fully automated workflow with the new `generate-mnemonic` command. There is no release yet but we'd like to get your feedback on it if you can run it from source. It's in the main branch.

**Comment by martin-braun** [comment]
@valefar-on-discord Thank you, I wasn't aware about sensitive ordering of the arguments, but if it's documented, there is nothing to complain in that regard. However, the confirmation prompting that cannot be silenced is still a problem, so is the noise output.

I want to report that I moved to `eth2-val-tools` which handles all of this nicely. It's unfortunate that it is not officially recommend to use, but it is very easy to audit and build from source, so whatever.

**Comment by yorickdowne** [comment]
Noting that this is still on the radar. I'll investigate. I agree that `--non-interactive` with `existing-mnemonic` should not cause prompts, unless a needed parameter was excluded on command line

**Comment by yorickdowne** [comment]
```
dist/deposit --non_interactive --ignore_connectivity generate-mnemonic --mnemonic_language english --output_file ./test-mnemonic.txt
```

Creates `./test-mnemonic.txt`, no prompts

```
dist/deposit --non_interactive --ignore_connectivity --language english existing-mnemonic --compounding --amount 512 --withdrawal_address 0xA0eDD952Fb2b17a0542490a18693e20191C02755 --chain mainnet --keystore_password SoVerySecretOMG --num_validators 1 --validator_start_index 0 --mnemonic "$(cat ./test-mnemonic.txt)"
```

Creates validators, no prompts

**Comment by yorickdowne** [comment]
@martin-braun I am glad you have a tool that works for you. A fully automated process works with this tool as well, since adding `generate-mnemonic`. I am closing this issue. Thanks for helping us make the tool better!
